# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'JDragonTypeButtonViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JDragonTypeButtonViewDemo
pod 'JDragonTypeButtonView', :path => '../JDragonTypeButtonView.podspec'  #指定podspec文件

  target 'JDragonTypeButtonViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JDragonTypeButtonViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
